version: 2
jobs:
  e2e:
    docker:
      - image: python:3.4.4
      - image: circleci/python:3.4-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Prepare end-to-end tests
          command: docker-compose -f docker-compose.e2e.yml up -d
      - run:
          name: Build app
          command: docker build -t celiangarcia/firefly-web:latest .
      - run:
          name: Execute end-to-end tests
          command: docker run -it --net="host" celiangarcia/firefly-web:latest npm run e2e

workflows:
  version: 2
  all:
    jobs:
      - e2e
