version: 2
jobs:
  e2e:
    machine: true
    environment:
      - IMAGE: "firefly-web"
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/bin/docker-compose
      - checkout
      - run:
          name: Prepare end-to-end tests
          command: docker-compose -f docker-compose.e2e.yml up -d
      - run:
          name: Build app
          command: docker build -t $DOCKER_USER/$IMAGE:`node -p -e "require('./package.json').version"` .
      - run:
          name: Execute end-to-end tests
          command: docker run -it --net="host" $DOCKER_USER/$IMAGE:`node -p -e "require('./package.json').version"` npm run e2e
  deploy:
    machine: true
    environment:
      - IMAGE: "firefly-web"
    steps:
      - checkout
      - run:
          name: Log in to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build image from Dockerfile
          command: docker build -t $DOCKER_USER/$IMAGE:`node -p -e "require('./package.json').version"` .
      - run:
          name: Push image to docker hub
          command: docker push $DOCKER_USER/$IMAGE:`node -p -e "require('./package.json').version"`

workflows:
  version: 2
  all:
    jobs:
      - e2e
      - deploy:
          requires:
            - e2e
          filters:
            branches:
              only: master
            tags:
              only: /.*/
